name: Deploy to Railway
on: { push: { branches: [ "main" ] }, workflow_dispatch: {} }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Railway CLI
        uses: actions/setup-node@v4

      - run: npm i -g @railway/cli@3

      - name: Link project
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Deploy (railway up)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service worker --ci