name: Deploy to Railway
on: { push: { branches: [ "main" ] }, workflow_dispatch: {} }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i -g @railway/cli@3
      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway --version
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --service worker --ci