name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Ставим Railway CLI (официального экшена от railwayapp нет)
      - name: Setup Railway CLI
        uses: MadeByThePinsHub/setup-railway-cli-action@v0.1.0

      - name: Railway version
        run: railway --version

      # Деплой в Railway через CLI
      - name: Deploy (railway up)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway status --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }} --service worker --ci
