name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Railway (worker)
        uses: railwayapp/action@v3
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          project: ${{ secrets.RAILWAY_PROJECT_ID }}
          service: worker
          command: python positions_guard.py --auto-cancel --no-pyramid
