name: Manual Deploy to Railway

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"
      service:
        description: "Railway service name"
        required: true
        default: "worker"

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check
        run: |
          python - <<'PY'
          import py_compile
          from pathlib import Path
          files = [p for p in Path('.').rglob('*.py')]
          failed = []
          for f in files:
            try:
              py_compile.compile(str(f), doraise=True)
            except Exception as e:
              failed.append(f"{f}: {e}")
          if failed:
            print("❌ Syntax errors:")
            for err in failed:
              print(" -", err)
            raise SystemExit(1)
          print(f"✅ OK: {len(files)} files compiled")
          PY

      - name: Import smoke
        run: |
          python - <<'PY'
          import importlib.util, sys
          from pathlib import Path
          main = Path("positions_guard.py")
          if not main.exists():
            print("⚠ positions_guard.py not found — skipping"); sys.exit(0)
          spec = importlib.util.spec_from_file_location("positions_guard", main)
          mod = importlib.util.module_from_spec(spec)
          try:
            spec.loader.exec_module(mod)
          except Exception as e:
            print("❌ Import error:", e); sys.exit(1)
          print("✅ positions_guard imported")
          PY

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          railway --version

      - name: Deploy to Railway (manual)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service="${{ github.event.inputs.service }}"
