name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # === Вариант A (рекомендуется): официальный Railway Action ===
      - name: Deploy to Railway (worker)
        uses: railwayapp/action@v3
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          # Если у проекта один сервис, Railway сам подхватит.
          # Явно укажем:
          service: worker
          # Если экшен «не находит» проект — раскомментируй project и добавь секрет:
           project: ${{ secrets.RAILWAY_PROJECT_ID }}
          # Можно задать старт-команду тут, если нет Procfile/Start Command:
          # command: python positions_guard.py --auto-cancel --no-pyramid

      # === Вариант B (CLI через shell) — оставь закомментированным, если не нужен ===
      # - name: Install Railway CLI
      #   run: npm i -g @railway/cli
      #
      # - name: Railway Up
      #   run: railway up --service=worker --ci
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
